spring:
  application:
    name: back
  spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL:localhost:5432/attusdb}
    username: ${SPRING_DATASOURCE_USERNAME:attus}
    password: ${SPRING_DATASOURCE_PASSWORD:At1vSD3}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

